= IpAddressBits.Or(IpAddressBits, IpAddressBits) Method
:root: ..
include::{root}/_common.adoc[tag=head]

== Definition
// tag::def[]
Combines two {type-ipab}[IpAddressBits] objects by binary or.
// end::def[]

== Overloads
[cols="a,"]
|===
// tag::overloads[]
| xref:./Or.adoc#ipaddressbits[] |
include::./Or.adoc[tag=desc-ipaddressbits]
| xref:./Or.adoc#ipaddressbits-ipaddressbits[] |
include::./Or.adoc[tag=def]
// end::overloads[]
|===

[[ipaddressbits]]
== Or(IpAddressBits)
// tag::desc-ipaddressbits[]
Combines an {type-ipab}[IpAddressBits] with another {type-ipab}[IpAddressBits] by binary or.
// end::desc-ipaddressbits[]
[source]
----
[IpAddressBits] Or([IpAddressBits] $other)
----

[discrete]
=== Parameters
`other` {type-ipab}[IpAddressBits]:: An IP address to combine.

[discrete]
=== Returns
{type-ipab}[IpAddressBits]:: The combination of the given address with this one.

[discrete]
=== Exceptions
{type-ane}[ArgumentNullException]:: `other` is `null`.

[[ipaddressbits-ipaddressbits]]
== Or(IpAddressBits, IpAddressBits)
include::./Or.adoc[tag=def]
[source]
----
[IpAddressBits] [IpAddressBits]::Or([IpAddressBits] $left, [IpAddressBits] $right)
----

[discrete]
=== Parameters
`left` {type-ipab}[IpAddressBits]:: An IP address to combine.
`right` {type-ipab}[IpAddressBits]:: An IP address to combine.

[discrete]
=== Returns
{type-ipab}[IpAddressBits]:: The combination of the two given addresses.

[discrete]
=== Exceptions
{type-ane}[ArgumentNullException]:: `left` or `right` is `null`.

== Related
xref:./And.adoc[]::
include::./And.adoc[tag=def]