= Get-SubNetwork
include::_common.adoc[tag=head]

Module: xref:../README.adoc[SubNetwork]

Gets information about a sub-network.

== Syntax
[source, subs="+attributes"]
----
Get-SubNetwork
    [[-Address] {syntax-ipab}]
    [-Bits] <byte>
    [<CommonParameters>]
----
[source, subs="+attributes"]
----
Get-SubNetwork
    [[-Address] {syntax-ipab}]
    [-Mask] {syntax-ipab}
    [<CommonParameters>]
----

== Description
The `Get-SubNetwork` function aggregates the `Get-BroadcastAddress`, `Get-NetworkAddress`, `Get-NetworkBits`, `Get-NetworkMask`, and `Measure-NetworkAddresses` functions, placing their output in an anonymous object for easy viewing or consumption.

== Examples
.Get sub-network information with network address and network bits
====
[source]
----
$NetworkInfo = Get-SubNetwork -Address 10.0.0.0 -Bits 8
----
This example calculates the network mask of the described network.
====

.Get sub-network information with address in network and network mask
====
[source]
----
$NetworkInfo = Get-SubNetwork -Address 192.168.1.42 -Mask 255.255.255.0
----
This example calculates the network address and network bits of the described network.
====

== Parameters
[discrete]
=== `-Address`
Specifies the IP address of the network, or an IP address within the network.

[cols="h,a"]
|===
include::_common.adoc[tag=types-ipab]
| Position | 0
| Default Value | None
| Accept Pipeline Input | True
| Accept Wildcard Characters | False
|===

[discrete]
=== `-Bits`
Specifies the number of network bits.

[cols="h,a"]
|===
| Type | {type-byte}[byte]
| Position | 1
| Default Value | None
| Accept Pipeline Input | False
| Accept Wildcard Characters | False
|===

[discrete]
=== `-Mask`
Specifies the network mask.

[cols="h,a"]
|===
include::_common.adoc[tag=types-ipab]
| Position | 1
| Default Value | None
| Accept Pipeline Input | False
| Accept Wildcard Characters | False
|===

== Inputs
include::_common.adoc[tag=input-ipab]

== Outputs
https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.pscustomobject[*PSCustomObject*]

This cmdlet returns a *PSCustomObject* with the following structure:

[source]
----
{
    [IpAddressBytes] 'Network Address'
    [IpAddressBytes] 'Broadcast Address'
    [UInt32] 'Addresses Assignable'
    [IpAddressBytes] 'Network Mask'
    [byte] 'Mask Bits'
}
----