= Get-NetworkAddress

Module: xref:../README.adoc[SubNetwork]

Gets the network address of a sub-network.

== Syntax
[source]
----
Get-NetworkAddress
    [-Address] <string> | <byte[]> | <IPAddress>
    [-Mask] <string> | <byte[]> | <IPAddress>
    [<CommonParameters>]
----
[source]
----
Get-NetworkAddress
    [-Address] <string> | <byte[]> | <IPAddress>
    [-Bits] <int>
    [<CommonParameters>]
----

== Description
The `Get-NetworkAddress` cmdlet determines the network address of a sub-network from an IP address within that sub-network and the information provided.

== Examples
.Get the network address of a given IP address with a given network mask.
====
[source]
----
Get-NetworkAddress -Address 192.168.0.32 -Mask 255.255.255.0
----
====

.Get the network address of a given IP address with a given number of network bits.
====
[source]
----
Get-NetworkAddress -Address 192.168.0.32 -Bits 24
----
====

.Get the network address of a given IP address as an IPAddress object
====
[source]
----
[System.Net.IPAddress] $NetworkAddress = Get-NetworkAddress -Address 10.0.0.250 -Bits 16 -Raw
----
====

== Parameters
[discrete]
=== `-Address`
Specifies an IP address within the sub-network.

[cols="h,a"]
|===
| Type | {type-string}[string], {type-byte}[byte[\]], or {type-ipaddress}[IPAddress]
| Position | Named
| Default Value | None
| Accept Pipeline Input | True
| Accept Wildcard Characters | False
|===

[discrete]
=== `-Mask`
Specifies the network mask.

[cols="h,a"]
|===
| Type | {type-string}[string], {type-byte}[byte[\]], or {type-ipaddress}[IPAddress]
| Position | Named
| Default Value | None
| Accept Pipeline Input | False
| Accept Wildcard Characters | False
|===

[discrete]
=== `-Bits`
Specifies the network mask bits.

[cols="h,a"]
|===
| Type | {type-int}[int]
| Position | Named
| Default Value | None
| Accept Pipeline Input | False
| Accept Wildcard Characters | False
|===

== Inputs
{type-string}[*string*], {type-byte}[*byte[\]*], {type-uint32}[*UInt32*], {type-ipaddress}[*IPAddress*], or {type-ipab}[*IpAddressBits]

You can pipe a *string*, *byte[]*, *UInt32*, *IPAddress* object, or *IpAddressBits* object to this cmdlet.

== Outputs
{type-ipab}[*IpAddressBits*]

This cmdlet returns an *IPAddressBits*. This object will coerce neatly to a {type-string}[*string*]