= Get-NetworkAddress
:source-language: powershell
:toc: left
:type-byte: https://docs.microsoft.com/en-us/dotnet/api/system.byte
:type-int: https://docs.microsoft.com/en-us/dotnet/api/system.int32
:type-ipaddress: https://docs.microsoft.com/en-us/dotnet/api/system.net.ipaddress
:type-string: https://docs.microsoft.com/en-us/dotnet/api/system.string
:type-switch: https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.switchparameter

Module: xref:../README.adoc[]

Gets the network address of a sub-network.

== Syntax
[source]
----
Get-NetworkAddress
    -Address [string] | [byte[]] | [IPAddress]
    -Mask [string] | [byte[]] | [IPAddress]
    [-Raw]
    [<CommonParameters>]
----
[source]
----
Get-NetworkAddress
    -Address [string] | [byte[]] | [IPAddress]
    -Bits [int]
    [-Raw]
    [<CommonParameters>]
----

== Description
The `Get-NetworkAddress` cmdlet determines the network address of a sub-network from an IP address within that sub-network and the information provided.

== Examples
.Get the network address of a given IP address with a given network mask.
====
[source]
----
Get-NetworkAddress -Address 192.168.0.32 -Mask 255.255.255.0
----
====

.Get the network address of a given IP address with a given number of network bits.
====
[source]
----
Get-NetworkAddress -Address 192.168.0.32 -Bits 24
----
====

.Get the network address of a given IP address as an IPAddress object
====
[source]
----
[System.Net.IPAddress] $NetworkAddress = Get-NetworkAddress -Address 10.0.0.250 -Bits 16 -Raw
----
====

== Parameters
[discrete]
=== `-Address`
Specifies an IP address within the sub-network.

[cols="h,a"]
|===
| Type | {type-string}[string], {type-byte}[byte[\]], or {type-ipaddress}[IPAddress]
| Position | Named
| Default Value | None
| Accept Pipeline Input | True
| Accept Wildcard Characters | False
|===

[discrete]
=== `-Mask`
Specifies the network mask.

[cols="h,a"]
|===
| Type | {type-string}[string], {type-byte}[byte[\]], or {type-ipaddress}[IPAddress]
| Position | Named
| Default Value | None
| Accept Pipeline Input | False
| Accept Wildcard Characters | False
|===

[discrete]
=== `-Bits`
Specifies the network mask bits.

[cols="h,a"]
|===
| Type | {type-int}[int]
| Position | Named
| Default Value | None
| Accept Pipeline Input | False
| Accept Wildcard Characters | False
|===

[discrete]
=== `-Raw`
Indicates that this cmdlet returns an *IPAddress* object. By default, this cmdlet outputs the network address as a well-formatted string.

|===
| Type | {type-switch}[SwitchParameter]
| Position | Named
| Default Value | None
| Accept Pipeline Input | False
| Accept Wildcard Characters | False
|===

== Inputs
{type-string}[*string*], {type-byte}[*byte[\]*], or {type-ipaddress}[*IPAddress*]

You can pipe a *string*, *byte[]* or *IPAddress* object to this cmdlet.

== Outputs
{type-string}[*string*] or {type-ipaddress}[*IPAddress*]

This cmdlet returns an *IPAddress* if the *Raw* parameter is specified. Otherwise this cmdlet outputs a *string*.