= Get-SubNetwork
:xroot: .
:source-language: powershell
:toc: left
:type-byte: https://docs.microsoft.com/en-us/dotnet/api/system.byte
:type-int: https://docs.microsoft.com/en-us/dotnet/api/system.int32
:type-ipaddress: https://docs.microsoft.com/en-us/dotnet/api/system.net.ipaddress
:type-ipab: xref:{xroot}/IpAddressBits/IpAddressBits.adoc
:type-string: https://docs.microsoft.com/en-us/dotnet/api/system.string
:type-switch: https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.switchparameter
:type-uint32: https://docs.microsoft.com/en-us/dotnet/api/system.uint32
:syntax-ipab: <byte[]> | <IPAddress> | <IpAddressBits> | <string> | <UInt32>
:type-ae: https://docs.microsoft.com/en-us/dotnet/api/system.argumentexception
:type-ane: https://docs.microsoft.com/en-us/dotnet/api/system.argumentnullexception
:type-aor: https://docs.microsoft.com/en-us/dotnet/api/system.argumentoutofrangeexception

Module: xref:../README.adoc[SubNetwork]

Gets information about a sub-network.

== Syntax
[source]
----
Get-SubNetwork
    [-Address] {syntax-ipab}
    [-Bits] <byte>
    [<CommonParameters>]
----
[source]
----
Get-SubNetwork
    [-Address] {syntax-ipab}
    [-Mask] {syntax-ipab}
    [<CommonParameters>]
----

== Description
The `Get-SubNetwork` function aggregates the `Get-BroadcastAddress`, `Get-NetworkAddress`, `Get-NetworkBits`, and `Get-NetworkMask` functions, placing their output in an anonymous object for easy viewing or consumption.

== Examples
.Get sub-network information with network address and network bits
====
[source]
----
$NetworkInfo = Get-SubNetwork -Address 10.0.0.0 -Bits 8
----
This example calculates the network mask of the described network.
====

.Get sub-network information with address in network and network mask
====
[source]
----
$NetworkInfo = Get-SubNetwork -Address 192.168.1.42 -Mask 255.255.255.0
----
This example calculates the network address and network bits of the described network.
====

== Parameters
[discrete]
=== `-Address`
Specifies the IP address of the network, or an IP address within the network.

[cols="h,a"]
|===
| Type | {type-byte}[byte[\]], {type-ipaddress}[IPAddress], {type-ipab}[IpAddressBits], {type-string}[string], or {type-uint32}[UInt32]
| Position | Named
| Default Value | None
| Accept Pipeline Input | True
| Accept Wildcard Characters | False
|===

[discrete]
=== `-Bits`
Specifies the number of network bits.

[cols="h,a"]
|===
| Type | {type-byte}[byte]
| Position | Named
| Default Value | None
| Accept Pipeline Input | False
| Accept Wildcard Characters | False
|===

[discrete]
=== `-Mask`
Specifies the network mask.

[cols="h,a"]
|===
| Type | {type-byte}[byte[\]], {type-ipaddress}[IPAddress], {type-ipab}[IpAddressBits], {type-string}[string], or {type-uint32}[UInt32]
| Position | Named
| Default Value | None
| Accept Pipeline Input | False
| Accept Wildcard Characters | False
|===

== Inputs
{type-byte}[*byte[\]*], {type-ipaddress}[*IPAddress*], {type-ipab}[*IpAddressBits], {type-string}[*string*], or {type-uint32}[*UInt32*]

You can pipe a *string*, *byte[]*, *UInt32*, *IPAddress* object, or *IpAddressBits* object to this function.

== Outputs
https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.pscustomobject[*PSCustomObject*]

This cmdlet returns a *PSCustomObject* with the following structure:

[source]
----
{
    [IpAddressBytes] 'Network Address'
    [IpAddressBytes] 'Broadcast Address'
    [IpAddressBytes] Mask
    [byte] 'Mask Bits'
}
----
